INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive) VALUES (1,'Mouse Mars Gaming Mmax Optico 12400DPI Iluminacion Chroma RGB Perforado Diseño Hive','#','https://i.ibb.co/C6JHRyY/img1.png','Mouse Mars Gaming Mmax Optico 12400DPI Iluminacion Chroma RGB Perforado Diseño Hive',35,10,'Mars Gaming','Periféricos e Impresoras','Mouse',0,'Rueda de deslizamiento, Macros, pies de Teflón, cable trenzado, rueda de desplazamiento con goma, 7 botones programables, sistema de iluminación Chroma, gold plated connector, iluminación multicolor RGB de 16,8 millones, interruptores HUANO, sensor óptico Pixart 3327PRO',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (2,'Notebook Asus Zenbook Pro 16X','#','https://i.ibb.co/BNgBchH/img2.png','Notebook Asus Zenbook Pro 16X',3130,5,'Asus','Laptop','Pro',0,'UX7602ZM-XB96T, Intel Core i9-12900H, 32GB, 2TB SSD, GeForce RTX 3060 6GB, 16',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (3,'Audífonos Inalámbricos Bluetooth Everest','#','https://i.ibb.co/cN8xgHC/img3.png','Audífonos Inalámbricos Bluetooth Everest',425,4,'JBL','Audífonos','Headphones',0,'JBL Everest 700 Inalámbrico Diseño Ergonómico Harman Recargable Bluetooth Ver4.0',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (4,'CPU con Procesador Dual Core de 2.36Ghz Generic','#','https://i.ibb.co/GdPvQNZ/img4.png','CPU con Procesador Dual Core de 2.36Ghz Generic',425,4,'AVR','Procesadores y CPU','CPU',0,'Disco Duro de 80GB, Memoria RAM de 2GB, Unidad Optica de DVD/CD RW+',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (5,'BM800 condensador profesional micrófono Podcast','#','https://i.ibb.co/Kx1FWJW/img5.png','BM800 condensador profesional micrófono Podcast',25,15,'AVR','Periféricos e Impresoras','Microphone',0,'Transmisión en directo equipo USB MIC Microfone de Studio Mic y soporte de grabación de música',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (6,'Monitor Samsung Curvo 32 Fhd 1960x1080 Hdmi Ultraslim 75hz','#','https://i.ibb.co/Hz0kyjf/img6.png','Monitor Samsung Curvo 32 Fhd 1960x1080 Hdmi Ultraslim 75hz',325,5,'Samsung','Monitores','Pro',0,'Soporte de colores: Máx. 16.7 M. Gama de colores (NTSC 1976): 72%. Frecuencia de actualización: Máx 75 Hz',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (7,'Audífonos bluetooth recargable live pods x20 Lenovo','#','https://i.ibb.co/fM5dhfJ/img7.png','Audífonos bluetooth recargable live pods x20 Lenovo',20,7,'Lenovo','Audífonos','Pro',0,'Tiempo de reproducción 6 horas continuas. Cancelación de ruido activa. Control de volumen. Bluetooth',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive) VALUES (8,'Audifonos Gaming Redragon Icon H520','#','https://i.ibb.co/xFrCTDK/img8.png','Audífonos Gaming Redragon Icon H520',70,15,'Redragon','Audífonos','Gaming',0,'Los Icon son auriculares con sonido envolvente 7.1 para experimentar bajos profundos, agudos claros y jugar con todos tus sentidos. Y su micrófono desmontable, se encargará de capturar cada una de tus palabras. Poseen además diadema metálica, flexible y cable mallado, como también un excelente aislamiento pasivo',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (9,'Mesa esquinera color negro','#','https://i.ibb.co/5410fNn/img9.png','Mesa esquinera color negro',300,5,'Comifort','Mobiliarios y sillas','Mobiliarios',0,'COMIFORT Escritorio Forma L - Mesa de Estudio Esquinera con Estantería de Estructura Firme, Moderna y Minimalista con 2 Baldas Espaciosas y de Gran Capacidad.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (10,'Laptop Asus F515 Intel I3 Memoria 8gb Ssd 128gb Windows 11','#','https://i.ibb.co/VM5jvgB/img10.png','Laptop Asus F515 Intel I3 Memoria 8gb Ssd 128gb Windows 11',375,7,'Asus','Laptop','Pro',0,'Laptop para juegos, pantalla IPS Full HD de 14 pulgadas, 144 Hz, 8 núcleos AMD Ryzen 9 5900HS, NVIDIA GeForce RTX 3060, Moonlight White-Tikbot Accesorios (16 GB RAM | 1 TB PCIe SSD)',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (11,'Procesador Intel Core I3 10100f 3,6 Ghz 10ma Gen Socket 1200','#','https://i.ibb.co/2sJZDjx/img11.jpg','Procesador Intel Core I3 10100f 3,6 Ghz 10ma Gen Socket 1200',125,6,'Intel','Procesadores y CPU','Procesadores',0,'Cantidad de núcleos 4. Cantidad de subprocesos 8. Frecuencia turbo máxima 4.40 GHz. Frecuencia de la Tecnología Intel® Turbo Boost 2.0‡ 4.40 GHz. Frecuencia básica del procesador 3.70 GHz',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (12,'Combo Core I3 10th Tarjeta Madreh510m-hv Ddr4 8gb 3200tforce','#','https://i.ibb.co/bsWQhYR/img12.jpg','Combo Core I3 10th Tarjeta Madreh510m-hv Ddr4 8gb 3200tforce',255,5,'Intel','Procesadores y CPU','Procesadores',0,'Soporta procesadores Intel® Core™ de 10ª generación y procesadores Intel® Core™ de 11ª generación (LGA1200). Soporta memoria DDR4 3200MHz*. 1 x PCIe 4.0 x16, 1 x PCIe 3.0 x1. Opciones de salida gráficos: HDMI, D-Sub',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive) VALUES (13,'Procesador Intel Core I7-10700f Caché De 16 M Hasta 4,80ghz','#','https://i.ibb.co/hsxQ6qz/img13.jpg','Procesador Intel Core I7-10700f Caché De 16 M Hasta 4,80ghz',400,4,'Intel','Procesadores y CPU','Procesadores',0,'Cantidad de núcleos: 8. Cantidad de subprocesos: 16. Frecuencia turbo máxima: 4,80 GHz. Frecuencia de la Tecnología Intel® Turbo Boost Max 3.0: 4,80 GHz. Frecuencia de la Tecnología Intel® Turbo Boost 2.0: 4.70 GHz. Frecuencia básica del procesador: 2,90 GHz',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive) VALUES (14,'Procesador Intel Core I5 12400f Socket Lga 1700 12va Gen','#','https://i.ibb.co/whFSkCG/img14.jpg','Procesador Intel Core I5 12400f Socket Lga 1700 12va Gen',200,5,'Intel','Procesadores y CPU','Procesadores',0,'Procesador Intel Core i5-12400F. 6 meses de garantía',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (15,'Nintendo Switch Edición Animal Crossing: New Horizons','#','https://i.ibb.co/QQx8sXX/img15.jpg','Nintendo Switch Edición Animal Crossing: New Horizons',350,10,'Nintendo','Consolas','Switch',0,'Nintendo Switch se inspira en el diseño del nuevo juego Animal Crossing: New Horizons, con hermosos controles Joy-Con de color verde pastel y azul que son blancos en la parte posterior, muñequeras blancas y un Nintendo Switch Dock blanco, adornado con imágenes de personajes reconocibles.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (16,'Nintendo Switch With Neon Blue And Neon Red','#','https://i.ibb.co/k0L1jMz/img16.jpg','Nintendo Switch With Neon Blue And Neon Red',450,7,'Nintendo','Consolas','Switch',0,'El nuevo sistema de videojuegos para casa de Nintendo. Además de proporcionar emociones individuales y multijugador en casa, el sistema Nintendo Switch se puede llevar para que los jugadores puedan disfrutar de una experiencia completa de consola en casa en cualquier momento y en cualquier lugar. La movilidad de una mano ahora se añade al poder de un sistema de juego en casa, con nuevos estilos de juego sin precedentes que cobran vida por los dos nuevos controles JoyCon.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (17,'Nintendo Switch Pro Control Joy-con','#','https://i.ibb.co/3z9k7JQ/img17.jpg','Nintendo Switch Pro Control Joy-con',110,10,'Nintendo','Consolas','Pro',0,'Lleva tus sesiones de juego a un nivel superior con el Nintendo Switch Pro Controller. Conmutador de Nintendo portátil a un gran precio. Viene con cable de carga (USB C a USB A).',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive) VALUES (18,'Nintendo Switch Oled Modelo 2021','#','https://i.ibb.co/9Tr3ctP/img18.jpg','Nintendo Switch Oled Modelo 2021',200,8,'Nintendo','Consolas','Pro',0,'Pantalla OLED de 7 pulgadas: disfruta de colores vivos y un contraste nítido con una pantalla que hace que los colores resalten. Puerto LAN con cable: utiliza el puerto LAN del dock cuando juegas en modo TV, para conectarte a Internet por cable. Almacenamiento interno de 64 GB: guarda juegos en tu sistema, con los 64 GB de almacenamiento interno.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (19,'Xbox Series S Versión Digital + Control Powera Original','#','https://i.ibb.co/hBNfWhj/img19.jpg','Xbox Series S Versión Digital + Control Powera Original',399.99,4,'Xbox','Consolas','Gaming',0,'Nueva Consola Xbox Series S Versión All Digital Completamente Sellada más Control Alámbrico de la Marca PowerA diseñado especialmente para Xbox. Disfruta de miles de juegos digitales entre cuatro generaciones de consolas Xbox.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (20,'Playstation 5 Standar Edition (lector De Discos) 825gb','#','https://i.ibb.co/jLS3sLc/img20.jpg','Playstation 5 Standar Edition (lector De Discos) 825gb',650,3,'Playstation','Consolas','Gaming',0,'Disfruta de la potencia de una CPU, una GPU y una SSD personalizadas con E/S integradas que redefinirá lo que una consola PlayStation puede hacer.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (21,'Acer Chromebook 311 Mini Laptop Cpu Octacore Ram 4gb 32gb','#','https://i.ibb.co/233dn6t/img21.jpg','Acer Chromebook 311 Mini Laptop Cpu Octacore Ram 4gb 32gb',145,10,'Acer','Laptop','Notebook',0,'Modelo de procesador: Intel Celeron. Garantía del fabricante - 12 Meses. Marca: Acer. Memoria del sistema (RAM): 4 gigabytes. Número de modelo del procesador: Intel® Celeron® N4020. Capacidad total de almacenamiento: 32 gigabytes',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (22,'Laptop Asus C423n De 14 PuLG 4gb/32gb N3350','#','https://i.ibb.co/8nyvYnt/img22.jpg','Laptop Asus C423n De 14 PuLG 4gb/32gb N3350',399,9,'Asus','Laptop','Notebook',0,'ASUS Chromebook C423 es la forma más sencilla de aumentar tu productividad y divertirte en movimiento, todo el día y cada día. Este ultraportátil y ligero Chromebook de 14 pulgadas está alimentado te ofrece la libertad de hasta 10 horas de autonomía de la batería. También es el primer ASUS Chromebook que incorpora un diseño NanoEdge, que te ofrece una gran pantalla en un chasis compacto para facilitar la multitarea y un entretenimiento más envolvente.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (23,'Laptop Asus Ryzen 3 3250u','#','https://i.ibb.co/zxp1fjm/img23.jpg','Laptop Asus Ryzen 3 3250u',450,10,'Asus','Laptop','Pro',0,'Memoria 8gb Disco 128gb Pant 14. Disco duro de 128GB SSD. Sistema Operativo Windows',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (24,'Laptop Dell Inspiron I3-1115g4 / 8 Ram / 128 Ssd / 1 Tb Hdd','#','https://i.ibb.co/S6d6wmX/img24.jpg','Laptop Dell Inspiron I3-1115g4 / 8 Ram / 128 Ssd / 1 Tb Hdd',650,7,'Dell','Laptop','Notebook',0,'Processor: 11th Generation Intel® Core™ i3-1115G4 Processor (6MB Cache, up to 4.1 GHz). Operating System: Windows 10 Home Single Language(64bit). Video Card: Intel® UHD Graphics with shared graphics memory. Display: 15.6-inch FHD (1920 x 1080) Anti-glare LED Backlight Non-Touch Narrow',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (25,'Asus 14 Intel Core I3-1115g4,ram 4gb ,m.2 Ssd 128gb','#','https://i.ibb.co/JsmS0bG/img25.jpg','Asus 14 Intel Core I3-1115g4,ram 4gb ,m.2 Ssd 128gb',490,8,'Asus','Laptop','Pro',0,'ALMACENAMIENTO: DISCO 128GB SSD M.2 NVMe. GRAFICOS: INTEL UHD. PANTALLA: 14 LED Full HD',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (26,'Laptop Asus Rog Zephyrus 14 Wqxga Ryzen 9 1tb Ssd 16gb Ddr5','#','https://i.ibb.co/3S6ThNY/img26.jpg','Laptop Asus Rog Zephyrus 14 Wqxga Ryzen 9 1tb Ssd 16gb Ddr5',890,10,'Asus','Laptop','Pro',0,'AMD Ryzen 9 6900HS (8 núcleos - 4.9 Ghz Max). 16Gb RAM DDR5 4800 Mhz. SSD 1TB PCIe 4.0 NVMe',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (27,'Laptop Dell Latitude E7270 Ultrabook','#','https://i.ibb.co/cNtM1ck/img27.jpg','Laptop Dell Latitude E7270 Ultrabook',999,6,'Dell','Laptop','Pro',0,'CPU Intel Core i5 6ta Generación. Velocidad Procesador 3.00 Ghz. Memoria RAM instalada 8 GB. S.O. Windows 10Pro 64 bits',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (28,'Laptop Gamer Asus Tuf 15,6 Intel Core I5 - 8gb 512ssd','#','https://i.ibb.co/0nhNWmB/img28.jpg','Laptop Gamer Asus Tuf 15,6 Intel Core I5 - 8gb 512ssd',1190,4,'Asus','Laptop','Gaming',0,'Su pantalla LED de 15.6 y 1920x1080 px de resolución te brindará colores más vivos y definidos. Tus películas y series preferidas cobrarán vida, ya que ganarán calidad y definición en cada detalle.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (29,'Notebook Hp Pavilion X360 Er0010ca 15.6 Touchscreen','#','https://i.ibb.co/x7t6m5h/img29.jpg','Notebook Hp Pavilion X360 Er0010ca 15.6 Touchscreen',919,8,'HP','Laptop','Notebook',0,'Capacidad total de almacenamiento: 256 GB. Medios de almacenamiento: SSD. Tipo de panel: IPS. Tipo HD: Full HD. Resolución de pantalla: 1920 x 1080 píxeles',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (30,'Notebook Hp 15-ec1046nr Gaming Ryzen 7-4800h 12gb 512gb','#','https://i.ibb.co/12NnXmV/img30.jpg','Notebook Hp 15-ec1046nr Gaming Ryzen 7-4800h 12gb 512gb',1400,7,'HP','Laptop','Gaming',0,'NOTEBOOK HP 15-ec1046nr gaming ryzen 7-4800h 12gb 512gb NEGRO',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (31,'Gigabyte G5 Core I5 11400H/16Gb/SSD PCIe 512Gb/RTX 3050 Ti/15,6 144Hz','#','https://i.ibb.co/Pmncx2z/img31.jpg','Gigabyte G5 Core I5 11400H/16Gb/SSD PCIe 512Gb/RTX 3050 Ti/15,6 144Hz',1750,10,'Intel','Laptop','Pro',0,'GIGABYTE G5 GD - 15.6 pulgadas FHD IPS antirreflejo 144Hz, Intel Core i5, NVIDIA GeForce RTX 3050 GPU 4GB GDDR6, 16GB de memoria, 512GB SSD',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (32,'IMPRESORA MULTIFUNCIONAL ECO TANK','#','https://i.ibb.co/NtNMPpG/img294.webp','IMPRESORA MULTIFUNCIONAL ECO TANK',399,5,'Epson','Periféricos e Impresoras','Impresoras',0,'La multinacional EcoTank L3110 te ofrece la revolucionaria impresión sin cartuchos, con nuevo diseño de tanques frontales, botellas de tinta con llenado automático y codificadas para llenado fácil de color. Con gran economía y tranquilidad en la impresión, la EcoTank L3110 te permite imprimir hasta 7.500 páginas a color1 o 4.500 páginas en negro1 con calidad profesional y alta velocidad',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (33,'Regulador de voltaje automático','#','https://i.ibb.co/zsK339g/img295.jpg','Regulador de voltaje automático',199,15,'APC','Fuentes, Tarjetas y Reguladores','Reguladores',0,'APC Line-R 500VA Regulador Automático de Voltaje, 3 Universal Outlets, 230V.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (34,'CAMARA TIPO DOMO VARIFOCAL  POE  2 MGPXL','#','https://i.ibb.co/Km5k09V/img296.webp','CAMARA TIPO DOMO VARIFOCAL  POE  2 MGPXL',85,17,'Techview','Seguridad','Cámaras',0,'Cámara De Seguridad Ip Domo Varifocal 2mp 1080p Antivandalic',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (35,'CAMARA BALA 3,6 mm, AHD, 1.3MP/960P, NTSC, 12V/2A, 36 LEDS','#','https://i.ibb.co/x2B7gfh/img297.webp','CAMARA BALA 3,6 mm, AHD, 1.3MP/960P, NTSC, 12V/2A, 36 LEDS',99,10,'Techview','Seguridad','Cámaras',0,'CAMARA BALA 3.6 MM AHD, 1.3MP/960P, NTSC, 12V/2A, 36 LEDS. FUNCIONA CON CABLE COAXIAL Y NO DE RED',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (36,'Teclado Multimedia Argom Usb Español Kb-7807','#','https://i.ibb.co/fX5BgZY/img298.webp','Teclado Multimedia Argom Usb Español Kb-7807',49,10,'Argom','Teclados','Multimedia',0,'TECLADO ARGOM ARG-KB-7807 MULTIMEDIA · Diseño atractivo y sensación cómoda de la mano · Diseño: teclas españolas',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (37,'Mouse Argomtech Gaming Combat Ms42 Usb Arg-ms-2042bk','#','https://i.ibb.co/DtxVgrx/img299.png','Mouse Argomtech Gaming Combat Ms42 Usb Arg-ms-2042bk',29,15,'Argom','Periféricos e Impresoras','Mouse',0,'Mouse gamer * Modelo: ARG-MS-2042BK * Marca: ARGOM TECH * Color: Negro * Conectividad: USB',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (38,'MOUSE INALÁMBRICO 2,4G ROJO ARGOM','#','https://i.ibb.co/PGyLz1P/img300.jpg','MOUSE INALÁMBRICO 2,4G ROJO ARGOM',19,10,'Argom','Periféricos e Impresoras','Mouse',0,'Mouse inalámbrico de 2.4GHz con 6 botones. Incluye botones de mando laterales (izquierdo y derecho) y botones de, frente, atrás, botón DPI y rueda scroll que permite alta precisión, uso prolongado y desempeño asegurado.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (39,'Fuente Cooler Master MWE Bronze 750W','#','https://i.ibb.co/6JVWt5W/img56.jpg','Fuente Cooler Master MWE Bronze 750W',125,9,'Cooler Master','Fuentes, Tarjetas y Reguladores','Fuentes',0,'Fuente de alimentación con certificación 80 PLUS Bronze. Tecnología DC a DC Ventilador HDB de 120 mm 80 PLUS Bronce Eficiencia',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (40,'Fuente ASUS TUF Gaming 550W Bronze','#','https://i.ibb.co/r6JspmG/img57.jpg','Fuente ASUS TUF Gaming 550W Bronze',134.99,10,'Asus','Fuentes, Tarjetas y Reguladores','Fuentes',0,'La fuente de alimentación ASUS TUF GAMING 550W Bronce PSU cuenta con una certificación 80 Plus Bronce para eficiencia energética, ventilador de 0 dB',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (41,'Regulador AVR FVR-1202C 1200VA/600W (3 en línea)','#','https://i.ibb.co/KmvkSs8/img62.jpg','Forza Regulador AVR FVR-1202C 1200VA/600W (3 en línea)',39,2,'AVR','Fuentes, Tarjetas y Reguladores','Fuentes',0,'FVR-1211USB · Capacidad: 1200VA/600W · Voltaje: 120V · Tipo de entrada: NEMA 5-15P · Tipo de salida: 8 x NEMA 5-15R · Indicador visual: Luz LED de estado',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (42,'Tarjeta BIOSTAR A520MH','#','https://i.ibb.co/BTFjc7Q/img66.jpg','BIOSTAR A520MH',90,5,'Tarjeta Biostar','Fuentes, Tarjetas y Reguladores','Tarjetas',0,'Biostar A520MH mATX placa base- Procesadores compatibles. AMD 3rd Generation Ryzen ; Tipo de set de chips. AMD A520 ; Velocidad de memoria del reloj. 2400 MHz',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (43,'Tarjeta Mother Asus TUF B550 Plus Gaming','#','https://i.ibb.co/djrfxBd/img69.jpg','Tarjeta Mother Asus TUF B550 Plus Gaming',289.99,12,'Asus','Fuentes, Tarjetas y Reguladores','Tarjetas',0,'Tarjeta madre para juegos AMD B550 (Ryzen AM4) ATX con PCIe 4.0, M.2 dual, 10 fases de poder DrMOS, Ethernet de 2.5 Gb, HDMI, DisplayPort, SATA 6 Gbps',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (44,'Tarjeta Mother MSI B550 GAMING EDGE WiFi','#','https://i.ibb.co/JQwb40J/img71.jpg','Tarjeta Mother MSI B550 GAMING EDGE WiFi',299,6,'AMD','Fuentes, Tarjetas y Reguladores','Tarjetas',0,'MPG B550 GAMING EDGE WIFI · Soporta procesadores 3ra Gen AMD Ryzen™ y futuros AMD Ryzen™ con actualización de BIOS · Soporta memoria DDR4 hasta 4866+(OC) MHz',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (45,'Asus TUF Gaming B660M-PLUS WiFi D4','#','https://i.ibb.co/Rc1c7BQ/img76.jpg','Asus TUF Gaming B660M-PLUS WiFi D4',299,10,'Asus','Fuentes, Tarjetas y Reguladores','Tarjetas',0,'Tarjeta madre B660 (LGA 1700) mATX, 10 + 1 fases de poder DrMOS, compatibilidad con PCIe 5.0, DDR4 5333 (OC), dos puertos M.2 PCIe 4.0',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (46,'Intel Dualcore G5905 Comet Lake','#','https://i.ibb.co/X4KRTzr/img89.jpg','Intel Dualcore G5905 Comet Lake',49,6,'Intel','Procesadores y CPU','Procesadores',0,'Procesador Intel Celeron G5905 Intel UHD Graphics 610, S-1200, 3.50GHz, Dual-Core, 4MB (10ma Generación Comet Lake) SKU: BX80701G5905',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (47,'Cooler DeepCool Gammaxx 400 V2 Red','#','https://i.ibb.co/KD54H9c/img100.jpg','Cooler Deepcool Gammaxx 400 V2 Red',33,6,'DeepCool','Accesorios','Cooler',0,'GAMMAXX 400 V2(Red) es una nueva edición de la legendaria serie GAMMAXX 400 con un ventilador mejorado de 120 mm con LEDs rojos',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (48,'Disipador DeepCool Gammaxx GTE v2 White','#','https://i.ibb.co/HhnWFHs/img103.jpg','Disipador DeepCool Gammaxx GTE v2 White',39,14,'DeepCool','Accesorios','Cooler',0,'Cubierta superior blanca con logotipo, premium y limpio · Ventilador PWM de 4.724 in con rendimiento mejorado e iluminación blanca',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (49,'Memoria Kingston Fury Beast RGB 8GB DDR4 3600Mhz','#','https://i.ibb.co/PrVzwLh/img131.jpg','Memoria Kingston Fury Beast RGB 8GB DDR4 3600Mhz',85,8,'Kingston','Periféricos e Impresoras','Memorias',0,'HyperX Kingston FURY™ DDR4 RGB ofrece velocidades de 2666 MT/s-3733 MT/s y capacidades de hasta 128 GB, y efectos de iluminación RGB dinámicos',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (50,'Memoria Adata XPG Hunter 16Gb DDR5 5200Mhz','#','https://i.ibb.co/swCMGT6/img133.jpg','Memoria Adata XPG Hunter 16Gb DDR5 5200Mhz',199,10,'Adata','Periféricos e Impresoras','Memorias',0,'Memoria DIMM Adata XPG HUNTER DDR5 PC5-41600 (5200MHz), CL38, 16GB',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (51,'Monitor LG 27MP60G-B IPS 75Hz','#','https://i.ibb.co/SBZs6TM/img162.jpg','Monitor LG 27MP60G-B IPS 75Hz',399,6,'LG','Monitores','Pro',0,'El LG 27MP60G-B es el monitor de alto rendimiento asequible que has estado esperando. La pantalla de clase de 27 pulgadas ofrece una claridad IPS Full HD',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (52,'Samsung Curvo C24F390FHL 24″','#','https://i.ibb.co/z6Mz6T2/img161.jpg','Monitor Samsung Curvo C24F390FHL 24″',295,7,'Samsung','Monitores','Curve',0,'Pantalla de 1.800R para mayor comodidad. Panel VA que evita fugas de luz.Imágenes superiores con tecnología avanzada. AMD FreeSync',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (53,'Monitor ASUS TUF VG249Q1R 165hz IPS','#','https://i.ibb.co/9ppXtPN/img163.jpg','Monitor ASUS TUF VG249Q1R 165hz IPS',399,9,'Asus','Monitores','Pro',0,'Monitor para juegos de 23.8 pulgadas Full HD (1920 x 1080), IPS, Overclockable 165Hz (por encima de 144Hz), 1ms MPRT, Extreme Low Motion Blur',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (54,'Silla HHGears SM115 Black','#','https://i.ibb.co/dGtmdyL/img173.jpg','Silla HHGears SM115 Black',164.99,5,'HHGears','Mobiliario y Sillas','Sillas',0,'El SM-115 está equipado con una buena gama de regulación de altura para asegurar que usted está en la posición óptima en relación con su escritorio. ',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (55,'Silla HHGears SM115 Black and Red','#','https://i.ibb.co/dGtmdyL/img173.jpg','Silla HHGears SM115 Black and Red',164.99,5,'HHGears','Mobiliario y Sillas','Sillas',0,'El SM-115 está equipado con una buena gama de regulación de altura para asegurar que usted está en la posición óptima en relación con su escritorio. ',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (56,'Silla HHGears SM115 Black and Green','#','https://i.ibb.co/dcGWv6j/img174.jpg','Silla HHGears SM115 Black and Green',164.99,5,'HHGears','Mobiliario y Sillas','Sillas',0,'El SM-115 está equipado con una buena gama de regulación de altura para asegurar que usted está en la posición óptima en relación con su escritorio. ',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (57,'Silla HHGears XL 300 Series Black and Red','#','https://i.ibb.co/t33Tjn9/img177.jpg','Silla HHGears XL 300 Series Black and Red',235,5,'HHGears','Mobiliario y Sillas','Sillas',0,'El XL-300 ofrece un nuevo nivel de comodidad para contornear y complementar el cuerpo del jugador. Para evitar el estrés repetitivo, tener la postura ergonómica',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (58,'Silla HHGears XL 300 Series Black and White','#','https://i.ibb.co/d2pDJv2/img178.jpg','Silla HHGears XL 300 Series Black and White',235,5,'HHGears','Mobiliario y Sillas','Sillas',0,'El XL-300 ofrece un nuevo nivel de comodidad para contornear y complementar el cuerpo del jugador. Para evitar el estrés repetitivo, tener la postura ergonómica',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (59,'Silla HHGears XL 300 Series Black','#','https://i.ibb.co/87m545f/img179.jpg','Silla HHGears XL 300 Series Black',235,5,'HHGears','Mobiliario y Sillas','Sillas',0,'El XL-300 ofrece un nuevo nivel de comodidad para contornear y complementar el cuerpo del jugador. Para evitar el estrés repetitivo, tener la postura ergonómica',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive) VALUES (60,'Silla HHGears XL 500 Series Black and Blue','#','https://i.ibb.co/TrWXPxp/img184.jpg','Silla HHGears XL 500 Series Black and Blue',325,4,'HHGears','Mobiliario y Sillas','Sillas',0,'El XL-500 presenta un diseño elegante con costuras con dibujos de diamantes en el respaldo y el asiento. el roscado de alta calidad define el nivel superior ',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (61,'Teclado Razer Cynosa V2 Chroma','#','https://i.ibb.co/3RjPsZN/img190.jpg','Teclado Razer Cynosa V2 Chroma',74.99,7,'Razer','Teclados','Pro',0,'CON TECNOLOGÍA RAZER CHROMA RGB. Personaliza este teclado para juegos RGB con más de 16,8 millones de colores y una amplia gama de efectos a elegir. ',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (62,'Teclado Razer Blackwidow V3','#','https://i.ibb.co/4JGypM3/img193.jpg','Teclado Razer Blackwidow V3',160,8,'Razer','Teclados','Gaming',0,'El teclado mecánico para juegos más icónico, ahora equipado con funciones mejoradas y más avanzadas, incluidos nuestros switches de renombre mundial.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (63,'Teclado Razer Pro Type Ultra','#','https://i.ibb.co/K5DN2xV/img194.jpg','Teclado Razer Pro Type Ultra',180,4,'Razer','Teclados','Pro',0,'Teclado mecánico Razer Pro Type Ultra inalámbrico: interruptores silenciosos y lineales, diseño ergonómico, tecnología HyperSpeed',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (64,'Teclado Logitech K230 Wireless','#','https://i.ibb.co/4JFY0wb/img199.jpg','Teclado Logitech K230 Wireless',22,5,'Logitech','Teclados','Pro',0,'Logitech LA Wireless Keyboard K230 LAT Spanish AMR01170083SIO RF inalámbrico QWERTY Inglés teclado ; Número de teclas',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (65,'Teclado Logitech POP Keys Coral Rose Inalámbrico','#','https://i.ibb.co/5sfBFs9/img203.jpg','Teclado Logitech POP Keys Coral Rose Inalámbrico',108.99,7,'Logitech','Teclados','Gaming',0,'Logitech POP Keys - Teclado mecánico inalámbrico con teclas Emoji personalizables, diseño compacto duradero, conectividad Bluetooth o USB',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (66,'Teclado Logitech POP Keys Fresh Vibes Inalámbrico','#','https://i.ibb.co/8gZf45n/img204.jpg','Teclado Logitech POP Keys Fresh Vibes Inalámbrico',108.99,7,'Logitech','Teclados','Gaming',0,'Logitech POP Keys - Teclado mecánico inalámbrico con teclas Emoji personalizables, diseño compacto duradero, conectividad Bluetooth o USB',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (67,'Teclado Logitech POP Keys Black/Yellow Inalámbrico','#','hhttps://i.ibb.co/VHfdWfK/img205.jpg','Teclado Logitech POP Keys Black/Yellow Inalámbrico',108.99,7,'Logitech','Teclados','Gaming',0,'Logitech POP Keys - Teclado mecánico inalámbrico con teclas Emoji personalizables, diseño compacto duradero, conectividad Bluetooth o USB',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (68,'Teclado Logitech G PRO Gaming','#','https://i.ibb.co/9vT2vdG/img207.jpg','Teclado Logitech G PRO Gaming',121,5,'Logitech','Teclados','Pro',0,'Teclado PRO X para gaming. Con interruptores mecánicos avanzados GX intercambiables, diseño sin teclado numérico, RGB LIGHTSYNC',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (69,'Teclado Logitech G915 TKL inalámbrico Blanco','#','https://i.ibb.co/CBsbxbY/img209.jpg','Teclado Logitech G915 TKL inalámbrico Blanco',289.99,4,'Logitech','Teclados','Pro',0,'Logitech G915 TKL Teclado mecánico inalámbrico RGB con tecnología inalámbrica LIGHTSPEED para juegos sin teclado numérico',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (70,'Teclado Híbrido Cooler Master MK110','#','https://i.ibb.co/BTVW59g/img210.jpg','Teclado Híbrido Cooler Master MK110',44.99,7,'Cooler Master','Teclados','Pro',0,'Teclado con cable Cooler Master MK110 negro RGB interruptor mem-chanical ',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (71,'Mouse Logitech M280 negro inalámbrico','#','https://i.ibb.co/Yp14rpW/img214.jpg','Mouse Logitech M280 negro inalámbrico',16.99,10,'Logitech','Periféricos e Impresoras','Mouse',0,'Logitech M280. Interfaz de aparato: RF sin fil, Tecnología de movimiento: Optique, Convient pour: Oficina.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (72,'Mouse Logitech M280 gris inalámbrico','#','https://i.ibb.co/3s0G6zq/img215.jpg','Mouse Logitech M280 gris inalámbrico',16.99,10,'Logitech','Periféricos e Impresoras','Mouse',0,'Logitech M280. Interfaz de aparato: RF sin fil, Tecnología de movimiento: Optique, Convient pour: Oficina.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (73,'Mouse Logitech M280 rojo inalámbrico','#','https://i.ibb.co/nfH4zQy/img216.jpg','Mouse Logitech M280 rojo inalámbrico',16.99,10,'Logitech','Periféricos e Impresoras','Mouse',0,'Logitech M280. Interfaz de aparato: RF sin fil, Tecnología de movimiento: Optique, Convient pour: Oficina.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive) VALUES (74,'Mouse Logitech PRO HERO','#','https://i.ibb.co/s5cpgCv/img219.jpg','Mouse Logitech PRO HERO',36.99,5,'Logitech','Periféricos e Impresoras','Mouse',0,'Pro para gaming. Con el sensor HERO 25K avanzado, seis botones programables, diseño ligero, sistema mecánico de tensión de botones',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (75,'Mouse Logitech G305 Lightspeed Inalámbrico K/DA','#','https://i.ibb.co/C7M2Mks/img220.jpg','Mouse Logitech G305 Lightspeed Inalámbrico K/DA',41.99,5,'Logitech','Periféricos e Impresoras','Mouse',0,'Mouse inalámbrico G305 con tecnología LightSpeed para tiempos de respuesta ultrarrápidos de 1 ms, sensor óptico avanzado HERO y 250 horas de batería',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (76,'Mouse Logitech G305 Lightspeed Inalámbrico','#','https://i.ibb.co/HBb0X40/img221.jpg','Mouse Logitech G305 Lightspeed Inalámbrico',43.99,5,'Logitech','Periféricos e Impresoras','Mouse',0,'Mouse inalámbrico G305 con tecnología LightSpeed para tiempos de respuesta ultrarrápidos de 1 ms, sensor óptico avanzado HERO y 250 horas de batería',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (77,'Mouse Redragon Storm Elite','#','https://i.ibb.co/n7Dd78W/img226.jpg','Mouse Redragon Storm Elite',50,5,'Redragon','Periféricos e Impresoras','Mouse',0,'Más ágil, más rápido y más preciso que los demás, el Storm Elite está concebido para ser el mejor y lo consigue.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (78,'Audífonos Razer Kraken X Lite 7.1','#','https://i.ibb.co/tBcrTv6/img227.jpg','Audífonos Razer Kraken X Lite 7.1',44.99,12,'Razer','Audífonos','Headphones',0,'Audífonos ultraligeros para videojuegos: apto para sonido Surround 7.1, con marco ligero y micrófono cardioide flexible, para PC, PS4',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (79,'Audífonos Razer Kraken Mercury','#','https://i.ibb.co/LQG5xsx/img231.jpg','Audífonos Razer Kraken Mercury',75,4,'Razer','Audífonos','Headphones',0,'El RAZER Kraken de 3ª generación es el auricular con cable para jugadores competitivos. Sus grandes controladores de 1.969 in ofrecen un sonido potente y claro.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (80,'Audífonos Razer Blackshark v2 con Tarjeta de Sonido USB','#','https://i.ibb.co/vjzz7d6/img232.jpg','Audífonos Razer Blackshark v2 con Tarjeta de Sonido USB',99,12,'Razer','Audífonos','Headphones',0,'Juega como un profesional con los auriculares para esports Razer BlackShark V2 X USB, que incorporan innovadores diafragmas de audio y un micrófono mejorado',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (81,'Audífonos Razer Kraken for Console','#','https://i.ibb.co/ZWVHgw5/img233.jpg','Audífonos Razer Kraken for Console',99,7,'Razer','Audífonos','Gaming',0,'Controles de audio en auriculares: incluye una rueda de control de volumen analógica y un interruptor de silencio de micrófono en el auricular para ajustes',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (82,'Audífonos Razer Hammerhead True Wireless Mercury','#','https://i.ibb.co/N2K6ydD/img235.jpg','Audífonos Razer Hammerhead True Wireless Mercury',35,7,'Razer','Audífonos','Headphones',0,'Auriculares inalámbricos diseñados para lograr una auténtica libertad de audio con una conexión de latencia ultrabaja que ofrece una calidad de sonido',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (83,'Audífonos Razer Kraken Kitty Edition -Chroma USB','#','https://i.ibb.co/xFfz74X/img236.jpg','Audífonos Razer Kraken Kitty Edition -Chroma USB',129,7,'Razer','Audífonos','Gaming',0,'Razer Kraken Kitty Edition. Tipo de producto: Auriculares, Estilo de uso: Diadema, Uso recomendado: Juego. Tecnología de conectividad: Alámbrico',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (84,'Audífonos RAZER KAIRA inalámbrico para Xbox','#','https://i.ibb.co/Kmz29JY/img237.jpg','Audífonos RAZER KAIRA inalámbrico para Xbox',119,7,'Razer','Audífonos','Gaming',0,'Auriculares inalámbricos para Xbox Series X listos para la competición, con micrófono cardioide Razer™ HyperClear y diafragmas de titanio de 50 mm Razer',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (85,'Audífonos Razer Blackshark V2 PRO White','#','https://i.ibb.co/THrSBSM/img239.jpg','Audífonos Razer Blackshark V2 PRO White',189.99,10,'Razer','Audífonos','Headphones',0,'Los auriculares inalámbricos definitivos para el juego competitivo, diseñados en colaboración con los mejores profesionales de los sports.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (86,'Audífonos HyperX Cloud Stinger Core (PS4, PS5)','#','https://i.ibb.co/fNmbMhB/img241-jpg.jpg','Audífonos HyperX Cloud Stinger Core (PS4, PS5)',89,5,'HiperX','Audífonos','Gaming',0,'Los Cloud Stinger Core son los auriculares básicos perfectos para el jugador de PlayStation que busca una gran calidad de sonido a un precio razonable.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (87,'Audífonos HyperX Cloud Stinger Core Wireless (PC, PS4, PS5)','#','https://i.ibb.co/zJ2Lk7K/img243.jpg','Audífonos HyperX Cloud Stinger Core Wireless (PC, PS4, PS5)',85,7,'HiperX','Audífonos','Gaming',0,'Los auriculares inalámbricos HyperX Cloud Stinger Core son ligeros y resistentes y están preparados para jugar en sistemas PS4™ y PS5™',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (88,'Audífonos HyperX Cloud Alpha S Blackout','#','https://i.ibb.co/d2spNLD/img245.jpg','Audífonos HyperX Cloud Alpha S Blackout',125,7,'HiperX','Audífonos','Gaming',0,'HyperX Cloud Alpha S - Auriculares para juegos de PC, sonido envolvente 7.1, graves ajustables, controladores de doble cámara, mezclador de chat',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (89,'Audífonos Hyperx Cloud Revolver 7.1','#','https://i.ibb.co/pWd791n/img247.jpg','Audífonos Hyperx Cloud Revolver 7.1',179,6,'HiperX','Audífonos','Gaming',0,'El HyperX Cloud Revolver está preparado con sonido envolvente HyperX 7.1 y un escenario de sonido más amplio para escuchar el audio del juego con precisión',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (90,'Audífonos JBL Headphone T500 On Ear White','#','https://i.ibb.co/fQ17gTb/img253.jpg','Audífonos JBL Headphone T500 On Ear White',59,15,'JBL','Audífonos','Pro',0,'Los auriculares JBL TUNE500 ofrecen un sonido JBL Pure Bass potente y un sistema Plug & Go (Enchufar y listo)',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (91,'Audífonos JBL Headphone Wave100 BT Truly Wireless Black','#','https://i.ibb.co/F67JnPD/img255.jpg','Audífonos JBL Headphone Wave100 BT Truly Wireless Black',65,7,'JBL','Audífonos','Pro',0,'Con el sonido JBL Deep Bass, estos auriculares True Wireless ponen color a tu día con hasta 20 horas de reproducción.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (92,'Audífonos JBL Headphone Wave100 BT Truly Wireless Ivory','#','https://i.ibb.co/hgqHnpd/img256.jpg','Audífonos JBL Headphone Wave100 BT Truly Wireless Ivory',65,7,'JBL','Audífonos','Pro',0,'Con el sonido JBL Deep Bass, estos auriculares True Wireless ponen color a tu día con hasta 20 horas de reproducción.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (93,'Mouse pad Razer Gigantus v2 M','#','https://i.ibb.co/0JgyBG8/img259.jpg','Mouse pad Razer Gigantus v2 M',14.99,5,'Razer','Periféricos e Impresoras','Mouse',0,'Alfombrilla de mouse para juegos (mediana): espuma gruesa y de alta densidad, base antideslizante, color negro clásico',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (94,'Logitech Webcam C270','#','https://i.ibb.co/Z1mJXWj/img264.jpg','Logitech Webcam C270',35.95,7,'Logitech','Periféricos e Impresoras','Webcam',0,'Ofrece alta definición 720p, 30 fps, micrófono de largo alcance, corrección de iluminación automática, visión de 55 grados',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (95,'Logitech Streamcam','#','https://i.ibb.co/0cB6CL4/img268.jpg','Logitech Streamcam',19.9,15,'Logitech','Periféricos e Impresoras','Webcam',0,'Logitech StreamCam hace streaming y graba con resolución Full HD 1080p a 60 fps, ofreciendo excepcional video con movimiento fluido para tu mundo online.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (96,'Control PowerA para Xbox Series X|S Nebula','#','https://i.ibb.co/LrXb2XT/img271.jpg','Control PowerA para Xbox Series X|S Nebula',49,10,'Xbox','Accesorios','Controles',0,'El controlador con cable mejorado PowerA para Xbox One está construido con nuestra última ergonomía y funciona en Xbox Series X|S.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (97,'Control Xbox Negro con cable para Windows','#','https://i.ibb.co/hRSLRDX/img273.jpg','Control Xbox Negro con cable para Windows',65,17,'Xbox','Accesorios','Controles',0,'Control Xbox 360 Microsoft Alambrico Usb Pc Microsoft ... Xbox 360 Slim Bateria Ni Mh 4800 Mah Y Cable Usb De Carga',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (98,'Cornetas Logitech Z313 2.1','#','https://i.ibb.co/pZ3WKNb/img276.jpg','Cornetas Logitech Z313 2.1',63.99,10,'Logitech','Accesorios','Cornetas',0,'Este sistema de bocinas 2.1 ofrece una acústica equilibrada y proporciona graves mejorados con un compacto subwoofer.',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (99,'Cornetas JBL Speaker Wind Bike mount BT Black','#','https://i.ibb.co/yQcm1m6/img280.jpg','Cornetas JBL Speaker Wind Bike mount BT Black',32.5,10,'JBL','Accesorios','Cornetas',0,'Altavoz Bluetooth portátil a prueba de salpicaduras para motocicletas, bicicletas y viajes al aire libre. Un altavoz todo en uno con radio FM incorporada',true);

INSERT INTO products (id, name, href, imageSrc, imageAlt, price, stock, brand, category, subcategory, rating, description, isActive)  VALUES (100,'Cornetas Logitech Z407 PC Bluetooth','#','https://i.ibb.co/x8GHR7D/img277.jpg','Cornetas Logitech Z407 PC Bluetooth',134.95,7,'Logitech','Accesorios','Cornetas',0,'Altavoces Bluetooth para computadora con subwoofer y control inalámbrico, sonido inmersivo, audio premium con múltiples entradas, altavoces USB',true);